# Generated by Django 5.1.5 on 2025-01-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_matrix_id', models.CharField(blank=True, max_length=255, null=True)),
                ('room_title', models.CharField(max_length=255)),
                ('room_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('room_visibility', models.CharField(blank=True, max_length=255, null=True)),
                ('room_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('room_version', models.CharField(blank=True, max_length=255, null=True)),
                ('room_type', models.CharField(blank=True, max_length=255, null=True)),
                ('room_federate', models.BooleanField(default=False)),
                ('room_is_direct', models.BooleanField(default=False)),
                ('room_preset', models.CharField(blank=True, max_length=255, null=True)),
                ('room_predessor', models.CharField(blank=True, max_length=255, null=True)),
                ('room_space', models.CharField(blank=True, max_length=255, null=True)),
                ('room_power_level_override', models.IntegerField(default=0)),
                ('room_invite', models.TextField(blank=True, null=True)),
                ('room_initial_state', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
