# Generated by Django 5.1.5 on 2025-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_file', models.FileField(upload_to='')),
                ('l_title', models.CharField(max_length=255)),
                ('l_description', models.TextField()),
                ('l_time', models.TimeField()),
                ('lc_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=255)),
                ('c_description', models.TextField()),
                ('c_type', models.CharField(choices=[('Audio', 'audio'), ('Video', 'video'), ('Photos', 'photos'), ('3D Models', '3d-models'), ('Code', 'code'), ('Finance', 'finance'), ('Cryptography', 'cryptography'), ('Science', 'science')], default='code', max_length=20)),
                ('c_prize', models.IntegerField()),
                ('c_addeting_files', models.BooleanField(default=False)),
                ('c_uploaded', models.DateTimeField(auto_now_add=True)),
                ('c_files', models.CharField(max_length=300)),
                ('c_rating', models.IntegerField(default=0)),
                ('c_bye_count', models.IntegerField(default=0)),
                ('c_pay_choices', models.CharField(choices=[('IBAN', 'iban'), ('Card number', 'card_number')], default='card_number', max_length=15)),
                ('c_lessons', models.ManyToManyField(related_name='cources', to='courceszone_sys.lessons')),
            ],
        ),
    ]
