# Generated by Django 5.1.4 on 2024-12-28 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_user_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(editable=False, max_length=255)),
                ('device_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255)),
                ('homeserver', models.CharField(default='matrix.org', max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
