# Generated by Django 5.1.5 on 2025-01-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiozone_sys', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('photozone_sys', '0001_initial'),
        ('projectzone_sys', '0001_initial'),
        ('videozone_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix_user_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('custom_pref', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('audio', models.ManyToManyField(blank=True, to='audiozone_sys.audio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('music', models.ManyToManyField(blank=True, to='audiozone_sys.music')),
                ('photos', models.ManyToManyField(blank=True, to='photozone_sys.photos')),
                ('project', models.ManyToManyField(blank=True, to='projectzone_sys.project')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('videos_long', models.ManyToManyField(blank=True, to='videozone_sys.longvideo')),
                ('videos_short', models.ManyToManyField(blank=True, to='videozone_sys.shortvideo')),
                ('current_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sm_user', to='auth_sys.matrixuser')),
                ('matrix_user', models.ManyToManyField(blank=True, related_name='sm_users', to='auth_sys.matrixuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
