# Generated by Django 5.1.5 on 2025-01-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiozone_sys', '0001_initial'),
        ('photozone_sys', '0001_initial'),
        ('projectzone_sys', '0001_initial'),
        ('videozone_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrix_user_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='SMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('custom_pref', models.JSONField()),
                ('audio', models.ManyToManyField(to='audiozone_sys.audio')),
                ('current_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_sm_user', to='auth_sys.matrixuser')),
                ('matrix_user', models.ManyToManyField(related_name='sm_users', to='auth_sys.matrixuser')),
                ('music', models.ManyToManyField(to='audiozone_sys.music')),
                ('photos', models.ManyToManyField(to='photozone_sys.photos')),
                ('project', models.ManyToManyField(to='projectzone_sys.project')),
                ('videos_long', models.ManyToManyField(to='videozone_sys.longvideo')),
                ('videos_short', models.ManyToManyField(to='videozone_sys.shortvideo')),
            ],
        ),
    ]
