# Generated by Django 5.1.5 on 2025-01-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuser',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_sm_user', to='auth_sys.matrixuser'),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='matrix_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='sm_users', to='auth_sys.matrixuser'),
        ),
    ]
