# Generated by Django 5.1.5 on 2025-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuser',
            name='authentificator',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
