# Generated by Django 5.1.5 on 2025-01-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixuser',
            name='user',
        ),
    ]
