# Generated by Django 5.1.5 on 2025-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_savedaccount'),
        ('photozone_sys', '0003_imgs4designscomments_photoscomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuser',
            name='imgs',
            field=models.ManyToManyField(blank=True, to='photozone_sys.imgs4designs'),
        ),
    ]
