# Generated by Django 5.1.5 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videozone_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_video', models.FileField(upload_to='')),
                ('size', models.CharField(max_length=60)),
                ('long', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.TextField()),
                ('share_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LongVideoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('long_video', models.ManyToManyField(related_name='comments', to='videozone_sys.longvideo')),
            ],
        ),
        migrations.CreateModel(
            name='ShortVideoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('short_video', models.ManyToManyField(related_name='comments', to='videozone_sys.shortvideo')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVideoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('template_video', models.ManyToManyField(related_name='comments', to='videozone_sys.templatevideo')),
            ],
        ),
    ]
