# Generated by Django 5.1.5 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectzone_sys', '0002_remove_project_project_remove_project_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('project', models.ManyToManyField(related_name='comments', to='projectzone_sys.project')),
            ],
        ),
    ]
