# Generated by Django 5.1.5 on 2025-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photozone_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs4Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('size', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.TextField()),
                ('share_title', models.CharField(max_length=255)),
            ],
        ),
    ]
