# Generated by Django 5.1.5 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photozone_sys', '0002_imgs4designs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs4DesignsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('image', models.ManyToManyField(related_name='comments', to='photozone_sys.imgs4designs')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('photo', models.ManyToManyField(related_name='comments', to='photozone_sys.photos')),
            ],
        ),
    ]
